### ISSUE TITLE
Not issues this is a Question/Suggestion/Request

### ISSUE THREAD

**Issue by keny10** [raweceek-temeletry/f1-22-udp#1]
HI, don't know if this is possible or not, i use the trhustmaster SF1000 wheel on xbox that use f1 2020 udp format only and since they don't provide update i would like to know if is possible to have f122 udp format and convert it to f1 2020 format so i can use a app that use f1 22 udp and forward to my wheel f1 2020 converted version 

i don't know if big change have been made between f122 and f1 2020 version 

so is it possible ? if so are you intesrested to make it ? 

Thanks you sorry to post issue can't find a way to contact you

**Comment by PrimeGoose** [comment]
If i had the same wheel and the same problem I would make it, there are big changes between formats, and sing i dont know how the weheel software validates the data received it would further complicate things. 

I would recomend using 2020 format in your f122 telemetry settings and app that supports it.

**Comment by keny10** [comment]
thanks for answer !
