### ISSUE TITLE
Error: Cannot find module 'node:dgram'

### ISSUE THREAD

**Issue by RobCoder44** [raweceek-temeletry/f1-22-udp#3]
Hi, love the work!

I have tried installing the f1 22 version and got the following error.

> Error: Cannot find module 'node:dgram'
> Require stack:
> - D:\sites\F1\f1-22\node_modules\f1-22-udp\build\src\F1_22_UDP.js
> - D:\sites\F1\f1-22\index.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:725:27)        
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> (D:\sites\F1\f1-22\node_modules\f1-22-udp\build\src\F1_22_UDP.js:5:22)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)        
>     at Module.require (internal/modules/cjs/loader.js:952:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'D:\\sites\\F1\\f1-22\\node_modules\\f1-22-udp\\build\\src\\F1_22_UDP.js',
>     'D:\\sites\\F1\\f1-22\\index.js'
>   ]
> }

I am using the default code to just launch the listener.

```
const { F122UDP } = require("f1-22-udp")
/*
*   'port' is optional, defaults to 20777
*   'address' is optional, defaults to localhost, in certain cases you may need to set address explicitly
*/

const f122 = new F122UDP()
f122.start();
// motion 0
f122.on('motion', function (data) {
    console.log(data);
})

f122.on("event", data => {
    console.log(data);
}) 
```

Thanks for any help.

Kind Regards

Rob

**Comment by PrimeGoose** [comment]
Try later node version

**Comment by LlamaCoin-cyber** [comment]
I am using the latest "node": "^18.5.0" in my package.json
