### ISSUE TITLE
LapData Event/Packet won't parse

### ISSUE THREAD

**Issue by EnKdev** [raweceek-temeletry/f1-22-udp#6]
Hey guys.

I have been using the UDP Library since last years game for a Discord RPC Client, and it worked like a charm back then.

This year, I also am using the UDP Library for the RPC Client of this years game, however, as I noticed, the LapData event is not entered when on-track during either a race or qualifying/practice sessions.

I am testing the entire app while I play and code at the same time to build the client, and as I ran a debugging session, I noticed that the execution of the code is halted during the time it reaches my instance of the parser with the LapData event specified, however, it simply won't enter at all.

The node version I am running is 14.15.3, NPM is running an older version, 7.19.0.

The code I have been using is essentially the same from the client app from last year, with just a little tweak to make place for the F2 game mode too.

The code I used for F1 2021:
```js
f1Client.on("lapData",  (lData) => {
    lapNumber = lData.m_lapData[19].m_currentLapNum;
    console.log(lData);
});
```

The code I try to run for F1 22:
```js
f1Client.on("lapData", (lData) => {
    if (formulaType === 2) { // F2 check
        lapNumber = lData.m_lapData[21].m_currentLapNum;
    } else {
        lapNumber = lData.m_lapData[19].m_currentLapNum;
    }
    console.log(lData);
});
```

If there is anything else I should provide or so, please let me know.
I liked how the Library worked last year, and it would be a bummer if something like this is suddenly not even fixable.

With regards
-EnKdev

**Comment by RobCoder44** [comment]
Where is `formulaType` defined?
Also is there a reason you are trying to get the last driver's current lap num. Surely you want the driver in first place lap num?

**Comment by RobCoder44** [comment]
Try this:

`f1Client.on("lapData", (lData) => {
  let lapNumber = 1;
  try {
    lData.m_lapData.forEach((ld) => {
      if (ld.m_currentLapNum > lapNumber) lapNumber = ld.m_currentLapNum;
    });
  } catch (e) {
    console.error("FAILED TO PARSE LAP NUMBER", e);
  }
  console.log(lapNumber);
});`

**Comment by RobCoder44** [comment]
Try this:
```
f1Client.on("lapData", (lData) => {
  let lapNumber = 1;
  try {
    lData.m_lapData.forEach((ld) => {
      if (ld.m_currentLapNum > lapNumber) lapNumber = ld.m_currentLapNum;
    });
  } catch (e) {
    console.error("FAILED TO PARSE LAP NUMBER", e);
  }
  console.log(lapNumber);
});
```

**Comment by EnKdev** [comment]
> Where is `formulaType` defined? Also is there a reason you are trying to get the last driver's current lap num. Surely you want the driver in first place lap num?

`formulaType` is defined in my parser for the session data.
It basically gets the current formula and then assigns it to a variable holding the number.

The reason why I want to get the last drivers current lap number is because in-game during the career mode, the player is always the last element in the participant array.

On top of that, I want to calculate the percentage of race completion based on the players current lap number and the total laps there are during a race.

**Comment by RobCoder44** [comment]
> 

Ok but in the header packet you get `m_playerCarIndex` that is your index. So you can always just use that for reference to you.

**Comment by EnKdev** [comment]
I'll note that down then.
Thanks for the help so far in advance, gonna try your suggestion out in a bit :)

**Comment by RobCoder44** [comment]
Cool, also its on "lap" not "lapData"
```
f1Client.on("lap", (lData) => {
});
```

**Comment by EnKdev** [comment]
> Cool, also its on "lap" not "lapData"
> 
> ```
> f1Client.on("lap", (lData) => {
> });
> ```

So wait, did the event change in terms of its name?
Because if so, then the readme did a sikes on me, as the list of available events lists "lapData" and not "lap" in the usage.png image

**Comment by RobCoder44** [comment]
Yeah in the code it has a lot named lapData but the emit function is this:
```
this.emit('lap', data);
```

So on you only listen on("lap") :/

**Comment by EnKdev** [comment]
Wish I would've known this earlier, the Readme doesn't reflect on this at all :/
Maybe that bit of information should be reflected into the readme, haha.
Kudos man, really wouldn't know what to do, now it actually jumps into the event, I can go forward from here on again!

**Comment by PrimeGoose** [comment]
this is the bug in the code
```ts
          case packetSize.LapData: {
            const {data} = new PacketLapDataParser(msg);
            this.emit('lap', data);

            break;
          }
          
```

this is the correct definition

  /**
  @event "lapData"
  @description `Frequency: Rate as specified in menus Size: 972 bytes`
   ```ts
    client.on('lapData', data => {
    const LapData:PacketLapData = data
    })
    ```
  */
  on(event: 'lapData', listener: (data: PacketLapData) => void): this; //2

  /**

**Comment by PrimeGoose** [comment]
```ts

 this.emit('lapData', data);
 ```
 the code will change to this
