### ISSUE TITLE
Issues with module declarations

### ISSUE THREAD

**Issue by BrunoBosko** [raweceek-temeletry/f1-22-udp#7]
Hello,
I'm currently trying to make a electron application, however there seems to be something wrong with some of the modules.

![image](https://user-images.githubusercontent.com/95883714/186122015-f088f8a8-8119-44d2-a83a-466fe6be948d.png)

If I try to build I get 12 errors of the same sort, all looking similiar to this:

```
node_modules/f1-22-udp/build/src/F1_22_UDP.d.ts:13:40 - error TS2307: Cannot find module 'Participants/types' or its corresponding type declarations.

13 import { PacketParticipantsData } from 'Participants/types';
```

How can I resolve this issue? 

Thanks in advance

**Comment by PrimeGoose** [comment]
there was a problem where d.ts files have not been sent to the build. renaming them to .ts files solved the issue.
