### ISSUE TITLE
Get own cars data

### ISSUE THREAD

**Issue by liscuate** [raweceek-temeletry/f1-22-udp#9]
Hello!

I would like to ONLY get my own car data such as speed, RPM etc, and not the other cars. How would I approach this?

**Comment by PrimeGoose** [comment]
every packet has a header object with PlayerCarIndex property you can use that to find your cars data in the array.
```js 

// approximate example
let myCar = data.carTelemetry[data.header.playerCarIndex]

console.log(myCar.rpm)

```
